version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nft-marketplace-db
    environment:
      POSTGRES_DB: nft_marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nft-marketplace

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: nft-marketplace-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nft-marketplace

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nft-marketplace-backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/nft_marketplace
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-for-development
      JWT_REFRESH_SECRET: your-refresh-secret-key-for-development
      ENCRYPTION_KEY: your-32-character-encryption-key-dev
      PINATA_API_KEY: your-pinata-api-key
      PINATA_SECRET_API_KEY: your-pinata-secret
      EMAIL_HOST: smtp.gmail.com
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-app-password
      ETHEREUM_RPC_URL: https://sepolia.infura.io/v3/your-project-id
      CONTRACT_ADDRESS: your-deployed-contract-address
      ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - nft-marketplace

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nft-marketplace-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_WALLET_CONNECT_PROJECT_ID: your-project-id
      REACT_APP_NETWORK_CHAIN_ID: "11155111"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - nft-marketplace

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: nft-marketplace-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - nft-marketplace
    profiles:
      - production

  # IPFS Node (Optional)
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: nft-marketplace-ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs_data:/data/ipfs
    networks:
      - nft-marketplace
    profiles:
      - ipfs

volumes:
  postgres_data:
  redis_data:
  ipfs_data:

networks:
  nft-marketplace:
    driver: bridge